language: java

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.m2

after_success:
  - ./deploy.sh
 
env:
  global:
    - GH_ACCOUNT=Holzschneider
    - GH_REPOSITORY=Fancy
    - secure: "reg9gqAp0qxKzaDQdNGgSw5nFqxUDlhFft8V6AeNzwjUKYN/8onAFVcfeQseQRq+qoNU/rftn1vsyEOMdY/4firC67LJLjFYBW1Csb9FpttPmVAFof9CuVED+bSVxSg0kx8nwgDALTvqGCWiLp3Cyek5uB6dry6KZ0BFoUBcaawHwsUGBZ+T7c+sU4CLyztE8AS2XuJDOETuPwFpwRhSSlNGSgqdzp/2h34Hl1p8RjrkaAI+cdiUdHDhyM/Dt6sYY2XXcLHvtrMmiJ+pAHA5vNLc5ME9a7gtU6gFokIjxi7dfUFJnHXPG9FmSB7pjwWWXycTpjwyVXv+2IekcsXKIU4SQHylmToLwIfvRcdhLnZWmXon3Ps7PYN/LmGpbWwJZoxfF2cPpnlbd1fYufYRI1sQLthvYsl17txdJyq815iN2Ql4hJZWVb/KCfAWvKK6GXi7M65ayaBonvCdxY+vvMf5j9no/kzYEgfFH5a78ySztTS/a3z6GDoi4nOlg53XuwaPYij8vxD4HPOAH93gI+lBzAJ8sTRCpXN67nkHV4JGDEVLMTkwSVR1s0N39FllXKH4s8Q+ZOpzLyNxasIEkTk8Aiv3uKy05BI3RwmavF3r22wpVulPm6E4BkKYzLcUzi6RK+P+0SasodMH4TxU9jA00mRBvy4ZmJuhsby3ZQs="
